import {
  AiFillApple,
  AiFillApi,
  AiFillBulb,
  AiFillBook,
  AiFillAliwangwang,
  AiFillCrown,
  AiFillDribbbleCircle,
  AiFillFormatPainter,
  AiFillSafetyCertificate,
  AiFillUsb,
  AiOutlineBarcode,
  AiOutlineClear,
  AiOutlineHeart,
  AiOutlineReddit,
  AiOutlineTrophy,
} from "react-icons/ai";

export const categories = [
  { name: "ITsub", icon: <AiFillBulb /> },
  { name: "underKG", icon: <AiFillDribbbleCircle /> },
  { name: "서울리안", icon: <AiFillFormatPainter /> },
  { name: "theEDIT", icon: <AiFillSafetyCertificate /> },
  { name: "방구석리뷰룸", icon: <AiFillBook /> },
  { name: "UPsub", icon: <AiFillAliwangwang /> },
  { name: "DragonLake", icon: <AiFillCrown /> },
  { name: "1분코딩", icon: <AiFillUsb /> },
  { name: "노마드코더", icon: <AiFillApi /> },
  { name: "코딩애플", icon: <AiFillApple /> },
  { name: "눈쟁이", icon: <AiOutlineTrophy /> },
  { name: "허수아비", icon: <AiOutlineReddit /> },
  { name: "딴트공 실험실", icon: <AiOutlineHeart /> },
  { name: "도레", icon: <AiOutlineClear /> },
  { name: "뻘짓연구소", icon: <AiOutlineBarcode /> },
];

// export const categories = [
//     { name: "00년생 공감 절대 불가능. 컴퓨터 저장장치의 변화 과정", icon: "w" },
//     { name: "학생덜,,,20년 전 피씨방 어떻게 생겼는지 궁금하지 않아👨‍🦳?(+ 김택진 리즈시절?!) ｜크랩, icon: 'j'" },
//     { name: "윈도우 시작과 끝, Windows 역사 총정리ㅣPOST IT", icon: "j" },
//     { name: "[옛날TV] 386 DOS 배우던 아이들이 상상한 미래의 컴퓨터 세상은??", icon: "j" },
//     { name: "1세대 컴퓨터부터 5세대 컴퓨터까지 세대별로 본 컴퓨터의 진화 총정리, 진공관에서 양자컴퓨터로 오기 까지", icon: "j" },
//     { name: "[미스테리] 세계 최초의 컴퓨터? 안티키테라 매커니즘 #shorts", icon: "j" },
//     { name: "IBM은 어떻게 탄생했을까? 인구 조사 기계를 만들던 회사에서 컴퓨터 기업이 되기까지 IBM의 초창기 이야기", icon: "j" },
//     { name: "맥북의 역사 | 맥북프로 : 세계관 끝판왕?", icon: "j" },
//     { name: "아빠가 대기업컴퓨터 사왔다! 잉? 23년전 삼성매직스테이션 ?", icon: "j" },
//     { name: "'컴퓨터'의 구조는 어떻게 되어있을까? CPU와 메모리! [안될과학 - 랩미팅 15화]", icon: "j" },
//     { name: "초창기 옛날 컴퓨터로 수업하는 모습 DOS Computer むかしのパソコン | 고전영상 옛날영상", icon: "j" },
//     { name: "[기업비사] 34회 : 대한민국 1호 벤처, 청계천에서 시작한 삼보컴퓨터", icon: "j" },
//     { name: "미국 산호세의 컴퓨터 역사 박물관(San Jose Computer History Museum)", icon: "j" },
//     { name: "인간 vs 컴퓨터…'숨막히는' 반세기 대결 역사", icon: "j" },
//     { name: "인간 vs 컴퓨터…'숨막히는' 반세기 대결 역사", icon: "j" },
//   ];
